# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: chiepom.me
email: chiepomme@0v0.cc
description: > # this means to ignore newlines until "baseurl:"
  fantasy music
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://chiepom.me" # the base hostname & protocol for your site
twitter_username: chiepomme
github_username: chiepomme

# Build settings
markdown: kramdown

# jekyll-seo-tag settings
author:
  twitter: chiepomme
twitter:
  username: chiepomme


gems:
  - jekyll-seo-tag